product_element = "img[alt='Customizable Desk']"
cart_btn = "a[aria-label='Shopping cart']"
proceed_to_checkout_btn = "button:has-text('Proceed to Checkout')"
checkbox_custom_legs = "input[type='checkbox'][value='1-7']"
product_cards = "td.oe_product"
product_titles = "td.oe_product h6.o_wsale_products_item_title a"
product_title_in_card = "h6.o_wsale_products_item_title a"
product_price_in_card = "span.oe_currency_value"
cart_quantity_label = "sup.my_cart_quantity"
