product_title = "#product_details h1[itemprop='name']"
product_price = "#product_details span.oe_price span.oe_currency_value"
product_color = "input[data-attribute_name='Color'][data-value_name='Black']"
product_image = "img.product_detail_img"
custom_leg = "input[data-attribute_name='Legs'][data-value_name='Custom']"
custom_input = "input[data-attribute_value_name='Custom']"
popup_custom_label = "span:text-is('Custom')"
popup_custom_value = "span:has-text('test')"
add_to_cart_btn = "#add_to_cart"
add_quantity_button = "a[aria-label='Add one']"
quantity_input = "#o_wsale_cta_wrapper input[name='add_qty']"
