name: Python autotest
on:
    workflow_dispatch:
    inputs: 
            deplayment_target:
              description: Choose test set
              required: true
              type: choice
              default: smoke
              options:
                      - smoke
                      - regression
                      - extended
                      - all

jobs:
  run_test:
  runs_on: ubuntu-latest
  name: Run autotests
  steps:
        - name: Checkout autotest
        uses: actions/checkout@v4
        - name: Set up Python environment
        uses: python-version:'3.10'
        - name: Install dependencies
        run: pip install -r requirements.txt
        - name: Run tests
        run: pytest
  
        
        
