name: Python autotest

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose test set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - extended
          - all

jobs:
  run_test:
    runs-on: ubuntu-latest
    name: Run autotests

    steps:
      - name: Checkout autotest
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run all tests
        if: "github.event.inputs.deployment_target=='all'"
        run: pytest

      - name: Run smoke tests
        if: "github.event.inputs.deployment_target=='smoke'"
        run: pytest -m smoke

      - name: Run regression tests
        if: "github.event.inputs.deployment_target=='regression'"
        run: pytest -m regression

      - name: Run extended tests
        if: "github.event.inputs.deployment_target=='extended'"
        run: pytest -m extended

        

        
